steps:
  # Init Terraform configuration
  - name: "hashicorp/terraform:latest"
    args: ["init"]
    dir: "terraform"

  # Apply Terraform configuration
  - name: "hashicorp/terraform:latest"
    args: ["apply", "-auto-approve"]
    dir: "terraform"
    env:
      - TF_VAR_project_id=$PROJECT_ID
      - TF_VAR_region=us-central1
      - TF_VAR_cluster_name=gke-cluster
  
  # Build Docker image for app
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/app:$COMMIT_SHA", "."]
    dir: "app"

  # Push Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/app:$COMMIT_SHA"]

  # Tag latest Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/$PROJECT_ID/app:$COMMIT_SHA", "gcr.io/$PROJECT_ID/app:latest"]

  # Push latest Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/app:latest"]

  # Deploy app to GKE and use latest image
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      [
        "run",
        "--filename=k8s/app.yaml",
        "--image=gcr.io/$PROJECT_ID/app:$COMMIT_SHA",
        "--location=us-central1",
        "--cluster=gke-cluster",
        "--output=./app-output",
      ]
  
  # Deploy stateful Postgres to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      [
        "run",
        "--filename=k8s/postgres.yaml",
        "--location=us-central1",
        "--cluster=gke-cluster",
        "--output=./postgres-output",
      ]
