apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: app
  name: app-service
spec:
  allocateLoadBalancerNodePorts: true
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: app
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: gcr.io/jpoehnelt-cohere-assignment/app:latest
          imagePullPolicy: IfNotPresent
          name: app
          ports:
            - containerPort: 3000
